USE windelsbe_db;
CREATE TABLE `vers_products` (
                                 `id` int NOT NULL,
                                 `sku` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
                                 `title` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
                                 `product_image` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
                                 `product_description` mediumtext COLLATE utf8mb4_general_ci,
                                 `amount_grams` decimal(10,3) NOT NULL,
                                 `unit` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
                                 `price_per_unit` decimal(10,2) NOT NULL,
                                 `extra_parts_price` decimal(10,2) DEFAULT NULL,
                                 `margin` decimal(5,2) DEFAULT NULL,
                                 `hours_worked` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
                                 `created_by_user` int DEFAULT NULL,
                                 `company_cost_per_product` decimal(10,2) DEFAULT '94.90',
                                 `sold_in_branches` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
                                 `vat_percentage` decimal(5,2) DEFAULT '21.00',
                                 `total_product_price` decimal(10,2) DEFAULT NULL,
                                 `created_on` date DEFAULT NULL,
                                 `shipping_method` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
                                 `category` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
                                 `stock` varchar(255) COLLATE utf8mb4_general_ci DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Gegevens worden geëxporteerd voor tabel `vers_products`
--

INSERT INTO `vers_products` (`id`, `sku`, `title`, `product_image`, `product_description`, `amount_grams`, `unit`, `price_per_unit`, `extra_parts_price`, `margin`, `hours_worked`, `created_by_user`, `company_cost_per_product`, `sold_in_branches`, `vat_percentage`, `total_product_price`, `created_on`, `shipping_method`, `category`, `stock`) VALUES
                                                                                                                                                                                                                                                                                                                                                          (1, '10015', 'Courgette', 'large_80c08fb0-e30f-4fdd-8977-d41bd4ebd70c.jpg', NULL, 0.000, 'stuk', 0.14, 0.00, 40.00, '00:30', 2, 0.58, '2', 6.00, 1.67, '2024-03-23', 'kleine_doos', 'vers', '0'),
                                                                                                                                                                                                                                                                                                                                                          (2, '10011', 'Tomaten', '20220117_085425239_iOS.jpg', NULL, 1.000, 'kg', 1.42, 0.00, 40.00, '00:30', 2, 0.58, '2', 6.00, 3.78, '2024-03-23', 'kleine_doos', 'vers', '0'),
                                                                                                                                                                                                                                                                                                                                                          (3, '10016', 'Sla', 'OIP.jpeg', NULL, 0.000, 'stuk', 0.14, 0.00, 40.00, '00:30', 2, 0.58, '2', 6.00, 1.67, '2024-03-23', 'kleine_doos', 'vers', '0'),
                                                                                                                                                                                                                                                                                                                                                          (4, '10013', 'Komkommer', 'graines-de-concombre.jpg', NULL, 0.400, 'stuk', 0.14, 0.00, 40.00, '00:30', 2, 0.58, '2', 6.00, 1.75, '2024-03-23', 'kleine_doos', 'vers', '0'),
                                                                                                                                                                                                                                                                                                                                                          (5, '10028', 'Rababer', 'rabarber-305.jpg', NULL, 1.000, 'kg', 1.13, 0.00, 40.00, '00:30', 2, 0.58, '2', 6.00, 3.35, '2024-03-23', 'kleine_doos', 'vers', '0'),
                                                                                                                                                                                                                                                                                                                                                          (6, '10014', 'Wortel', 'wortel.jpg', NULL, 1.000, 'kg', 0.71, 0.00, 40.00, '00:30', 2, 0.58, '2', 6.00, 2.72, '2024-03-23', 'kleine_doos', 'vers', '0'),
                                                                                                                                                                                                                                                                                                                                                          (7, '1002282', 'Gele paprika', 'R.jpg', NULL, 0.150, 'stuk', 0.14, 0.00, 40.00, '00:30', 2, 0.58, '2', 6.00, 1.70, '2024-03-23', 'kleine_doos', 'vers', '0'),
                                                                                                                                                                                                                                                                                                                                                          (8, '1002283', 'Oranje paprika', 'R.jpg', NULL, 0.150, 'stuk', 0.14, 0.00, 40.00, '00:30', 2, 0.58, '2', 6.00, 1.70, '2024-03-23', 'kleine_doos', 'vers', '0'),
                                                                                                                                                                                                                                                                                                                                                          (9, '100228', 'Rood paprika', 'R.jpg', NULL, 0.150, 'stuk', 0.14, 0.00, 40.00, '00:30', 2, 0.58, '2', 6.00, 1.70, '2024-03-23', 'kleine_doos', 'vers', '0'),
                                                                                                                                                                                                                                                                                                                                                          (10, '1002281', 'Groen paprika', 'R.jpg', NULL, 0.150, 'stuk', 0.14, 0.00, 40.00, '00:30', 2, 0.58, '2', 6.00, 1.70, '2024-03-23', 'kleine_doos', 'vers', '0'),
                                                                                                                                                                                                                                                                                                                                                          (26, '10030', 'Rabarber confituur', '../product_img/IMG_1865 2024-06-11 09_10_55.jpg', NULL, 1.000, 'stuk', 1.04, 0.00, 40.00, '00:30', 2, 0.58, '2', 6.00, 3.21, '2024-08-09', 'klein_doos', 'vers', '0'),
                                                                                                                                                                                                                                                                                                                                                          (27, '10031', 'prei', '../product_img/بصل-اخضر-1.jpg', NULL, 0.800, 'kg', 1.25, 0.00, 40.00, '00:00', 2, 0.68, '2', 6.00, 2.49, '2024-09-30', 'klein_doos', 'vers', '0'),
                                                                                                                                                                                                                                                                                                                                                          (28, '10064', 'Prei-corugettesoep', 'IMG_2633 2024-10-02 18_52_34.jpg', '', 9.000, 'stuk', 0.85, 0.00, 40.00, '00:10', 2, 0.68, '2', 6.00, 12.58, '2024-10-02', 'klein_doos', 'vers', '13');
